name: parcels
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bottleneck
  - cartopy
  - cftime
  - cmocean
  - dask=2021.02.0
  - distributed
  - ffmpeg
  - ipykernel
  - netCDF4
  - openblas
  - papermill
  - parcels=2.2.2
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - xarray
  - xhistogram
  - zarr
