name: parcels
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - basemap
  - bottleneck
  - cartopy
  - cftime
  - cmocean
  - curl
  - dask
  - dask=2022.6.1
  - datashader
  - distributed
  - ffmpeg
  - geopandas
  - geoviews
  - git
  - git-lfs
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - ipykernel
  - matplotlib
  - netcdf4
  - numcodecs
  - numpy
  - openblas
  - pandas
  - papermill
  - parcels=2.3.1
  - pip
  - python-blosc
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - sparse
  - xarray
  - xhistogram
  - xoak
  - zarr
