name: parcels
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - basemap
  - bottleneck
  - cartopy
  - cftime
  - cmocean
  - curl
  - dask
  - dask
  - datashader
  - distributed
  - ffmpeg
  - geopandas
  - geoviews
  - git
  - git-lfs
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - ipykernel
  - matplotlib
  - netcdf4
  - neutralocean
  - numcodecs
  - numpy
  - openblas
  - pandas
  - papermill
  - parcels=2.4.2
  - pip
  - pys2index
  - python-blosc
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - sparse
  - xarray
  - xhistogram
  - xoak
  - zarr
  - pip:
    - dask-labextension
