name: parcels
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - basemap
  - bottleneck
  - cartopy
  - cftime
  - cmocean
  - curl
  - dask
  - dask
  - datashader
  - distributed
  - ffmpeg
  - geopandas
  - geoviews
  - git
  - git-lfs
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - ipykernel
  - jupyter-archive
  - matplotlib
  - netcdf4
  - neutralocean
  - numcodecs
  - numpy
  - openblas
  - openpyxl
  - pandas
  - papermill
  - parcels=3.1.2
  - pip
  - pys2index
  - python-blosc
  - rasterio
  - regionmask
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - sparse
  - unzip
  - xarray
  - xhistogram
  - xoak
  - zarr
  - zip
  - pip:
    - dask-labextension
    - git+https://github.com/willirath/hextraj.git@2023.2.20.1
    - git+https://git.geomar.de/python/xorca_brokenline.git@f1bbcb1f791ee4d428d4fc6fe440263455389676
    - git+https://git.geomar.de/python/xorca_lonlat2ij.git@d9ab6ab959e3079183e9d7f729b5e98b2f5d9f73
