name: build-and-push

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE_NAME: "quay.io/willirath/parcels-container"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          CALVER_IMAGE=$IMAGE_NAME:${CALVER}-${SHA7}
          LATEST_IMAGE=$IMAGE_NAME:latest
          echo "CALVER_IMAGE=${CALVER_IMAGE}" >> $GITHUB_ENV
          echo "LATEST_IMAGE=${LATEST_IMAGE}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v1

      - name: Login to quay.io registry
        if: ${{ startsWith(github.ref, 'refs/heads/main')}}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: "${{env.LATEST_IMAGE}}, ${{env.CALVER_IMAGE}}"
          push: ${{ startsWith(github.ref, 'refs/heads/main')}}
