name: build-and-push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to quay.io registry
        if: ${{ startsWith(github.ref, 'refs/heads/main')}}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          repository: willirath/parcels-container
          tag: latest
          push: ${{ startsWith(github.ref, 'refs/heads/main')}}
